/**
 * Demo Script - StaticWaves POD Studio
 * Demonstrates all new features:
 * 1. Product Auto-Linking
 * 2. Price Lock-In Logic
 * 3. Multi-Region Feeds
 * 4. White-Label SaaS
 */

import { ProductLinker } from './services/productLinker';
import { PricingEngine } from './services/pricingEngine';
import { FeedGenerator } from './services/feedGenerator';
import { TenantManager } from './services/tenantManager';
import { IntegrationManager } from './services/integrations';
import { TikTokVideo, Product, Region } from './types';

// === MOCK DATA ===

const mockVideos: TikTokVideo[] = [
  {
    id: 'vid_001',
    url: 'https://tiktok.com/@user/video/001',
    caption: 'Check out my new workout gear! Perfect for fitness enthusiasts #fitness #activewear #gym',
    hashtags: ['fitness', 'activewear', 'gym', 'workout'],
    views: 150000,
    likes: 12000,
    createdAt: '2025-12-20T10:00:00Z',
    metadata: {
      duration: 30,
      thumbnail: 'https://picsum.photos/200/200',
      audioName: 'Workout Beat',
      mentions: ['@fitnessbrand'],
      location: 'Los Angeles, CA'
    }
  },
  {
    id: 'vid_002',
    url: 'https://tiktok.com/@user/video/002',
    caption: 'Loving this minimalist home decor aesthetic ✨ #homedecor #minimalist #interior',
    hashtags: ['homedecor', 'minimalist', 'interior', 'aesthetic'],
    views: 89000,
    likes: 7500,
    createdAt: '2025-12-22T14:30:00Z',
    metadata: {
      duration: 45,
      thumbnail: 'https://picsum.photos/200/201',
      audioName: 'Calm Vibes',
      mentions: [],
      location: 'New York, NY'
    }
  }
];

const mockProducts: Product[] = [
  {
    id: 'prod_001',
    name: 'Premium Fitness T-Shirt',
    description: 'High-performance athletic wear designed for intense workouts',
    tags: ['fitness', 'activewear', 'tshirt', 'sports'],
    basePrice: 29.99,
    regionalPricing: {
      US: 29.99,
      EU: 27.59,
      UK: 23.69
    },
    images: ['https://picsum.photos/800/800'],
    blueprintId: 6
  },
  {
    id: 'prod_002',
    name: 'Minimalist Wall Art Print',
    description: 'Modern abstract art for contemporary home interiors',
    tags: ['homedecor', 'art', 'minimalist', 'wallart'],
    basePrice: 39.99,
    regionalPricing: {
      US: 39.99,
      EU: 36.79,
      UK: 31.59
    },
    images: ['https://picsum.photos/800/801'],
    blueprintId: 12
  },
  {
    id: 'prod_003',
    name: 'Gym Motivation Poster',
    description: 'Inspirational fitness poster for home gyms',
    tags: ['fitness', 'gym', 'poster', 'motivation'],
    basePrice: 24.99,
    regionalPricing: {
      US: 24.99,
      EU: 22.99,
      UK: 19.74
    },
    images: ['https://picsum.photos/800/802'],
    blueprintId: 12
  }
];

// === DEMO FUNCTIONS ===

async function demoProductLinking() {
  console.log('\n=== 1. PRODUCT AUTO-LINKING DEMO ===\n');

  const linker = new ProductLinker(mockProducts);

  for (const video of mockVideos) {
    console.log(`Processing video: "${video.caption.slice(0, 50)}..."`);
    console.log(`  Views: ${video.views.toLocaleString()} | Likes: ${video.likes.toLocaleString()}`);

    const links = await linker.linkVideoToProducts(video);

    console.log(`  Found ${links.length} potential product matches:\n`);

    links.forEach((link, idx) => {
      const product = mockProducts.find(p => p.id === link.productId);
      console.log(`  ${idx + 1}. ${product?.name}`);
      console.log(`     Confidence: ${(link.confidence * 100).toFixed(1)}%`);
      console.log(`     Tags: ${link.tags.join(', ')}`);
      console.log(`     Auto-generated: ${link.autoGenerated ? 'Yes' : 'No'}\n`);
    });

    // Auto-generate tags
    const autoTags = ProductLinker.autoGenerateTags(video);
    console.log(`  Auto-generated tags: ${autoTags.join(', ')}\n`);
  }
}

async function demoPriceLockIn() {
  console.log('\n=== 2. PRICE LOCK-IN LOGIC DEMO ===\n');

  const pricingEngine = new PricingEngine();

  // Create price buckets for testing
  const product = mockProducts[0];
  console.log(`Testing prices for: ${product.name}\n`);

  const testPrices = [24.99, 29.99, 34.99];
  const regions = [Region.US, Region.EU, Region.UK];

  const buckets = pricingEngine.createPriceBuckets(product.id, testPrices, regions);
  console.log(`Created ${buckets.length} price buckets for A/B testing\n`);

  // Simulate traffic and conversions
  console.log('Simulating traffic and conversions...\n');

  buckets.forEach(bucket => {
    // Simulate impressions
    const impressions = Math.floor(Math.random() * 500) + 100;
    for (let i = 0; i < impressions; i++) {
      pricingEngine.trackImpression(bucket.id);
    }

    // Simulate conversions (lower prices convert better)
    const baseConversionRate = bucket.price < 30 ? 0.04 : 0.02;
    const conversions = Math.floor(impressions * baseConversionRate);

    for (let i = 0; i < conversions; i++) {
      pricingEngine.trackConversion(
        product.id,
        bucket.id,
        bucket.price,
        bucket.region,
        'tiktok'
      );
    }
  });

  // Evaluate and disable losers
  const { disabled, winners } = pricingEngine.evaluateAndDisableLosers();

  console.log(`Analysis complete:`);
  console.log(`  Winners: ${winners.length} price buckets`);
  console.log(`  Disabled: ${disabled.length} underperforming buckets\n`);

  // Show analytics
  const analytics = pricingEngine.getProductAnalytics(product.id);

  console.log('Product Analytics:');
  console.log(`  Total Revenue: $${analytics.totalRevenue.toFixed(2)}`);
  console.log(`  Total Conversions: ${analytics.totalConversions}`);
  console.log(`  Overall Conversion Rate: ${(analytics.overallConversionRate * 100).toFixed(2)}%\n`);

  console.log('By Region:');
  Object.entries(analytics.byRegion).forEach(([region, data]) => {
    console.log(`  ${region}:`);
    console.log(`    Revenue: $${data.revenue.toFixed(2)}`);
    console.log(`    Conversion Rate: ${(data.conversionRate * 100).toFixed(2)}%`);
    console.log(`    Winning Price: $${data.winningPrice?.toFixed(2) || 'N/A'}\n`);
  });

  // Lock in winning prices
  const lockedPrices = pricingEngine.lockInWinningPrices(product.id);
  console.log('Locked in winning prices:');
  Object.entries(lockedPrices).forEach(([region, price]) => {
    console.log(`  ${region}: $${price.toFixed(2)}`);
  });
}

async function demoMultiRegionFeeds() {
  console.log('\n\n=== 3. MULTI-REGION FEEDS DEMO ===\n');

  const feedGenerator = new FeedGenerator();

  console.log('Generating feeds for all regions...\n');

  const feeds = await feedGenerator.generateAllRegionFeeds(mockProducts, 'json');

  feeds.forEach(feed => {
    console.log(`${feed.region} Feed:`);
    console.log(`  Currency: ${feed.currency}`);
    console.log(`  Products: ${feed.products.length}`);
    console.log(`  Format: ${feed.format}`);
    console.log(`  Generated: ${new Date(feed.generatedAt).toLocaleString()}\n`);

    // Show first product pricing
    if (feed.products.length > 0) {
      const product = feed.products[0];
      const price = feedGenerator.getRegionalPrice(product, feed.region);
      console.log(`  Example: ${product.name}`);
      console.log(`    Price: ${feed.currency} ${price.toFixed(2)}\n`);
    }
  });

  // Export feeds in different formats
  console.log('Exporting feeds in multiple formats...\n');

  const formats: ('json' | 'xml' | 'csv')[] = ['json', 'xml', 'csv'];

  for (const format of formats) {
    const usFeed = await feedGenerator.generateRegionalFeed(
      mockProducts,
      Region.US,
      format
    );

    const exported = feedGenerator.exportFeed(usFeed);

    console.log(`${format.toUpperCase()} Export (US):`);
    console.log(`  Size: ${exported.length} characters`);
    console.log(`  Preview: ${exported.slice(0, 100)}...\n`);
  }
}

async function demoWhiteLabelSaaS() {
  console.log('\n=== 4. WHITE-LABEL SAAS DEMO ===\n');

  const tenantManager = new TenantManager();
  const integrationManager = new IntegrationManager();

  // Create tenants with different plans
  console.log('Creating tenant accounts...\n');

  const freeTenant = tenantManager.createTenant(
    'Startup Prints',
    'startup@example.com',
    'free'
  );

  const proTenant = tenantManager.createTenant(
    'Pro Merch Co',
    'pro@example.com',
    'pro'
  );

  console.log(`Created ${tenantManager.getAllTenants().length} tenants:\n`);

  [freeTenant, proTenant].forEach(tenant => {
    console.log(`${tenant.name} (${tenant.plan}):`);
    console.log(`  Slug: ${tenant.slug}`);
    console.log(`  API Key: ${tenant.apiKey.slice(0, 20)}...`);
    console.log(`  Features:`);
    console.log(`    Auto-Linking: ${tenant.settings.features.autoLinking ? 'Yes' : 'No'}`);
    console.log(`    Price Lock-In: ${tenant.settings.features.priceLockIn ? 'Yes' : 'No'}`);
    console.log(`    Multi-Region: ${tenant.settings.features.multiRegion ? 'Yes' : 'No'}`);
    console.log(`    Max Products: ${tenant.settings.features.maxProducts}\n`);
  });

  // Test feature validation
  console.log('Testing feature access control...\n');

  const freeAccess = tenantManager.validateAction(freeTenant.id, 'use_auto_linking');
  console.log(`Free tenant auto-linking: ${freeAccess.allowed ? 'Allowed' : 'Denied'}`);
  if (!freeAccess.allowed) console.log(`  Reason: ${freeAccess.reason}`);

  const proAccess = tenantManager.validateAction(proTenant.id, 'use_price_lock_in');
  console.log(`Pro tenant price lock-in: ${proAccess.allowed ? 'Allowed' : 'Denied'}\n`);

  // Set up integrations
  console.log('Setting up integrations for Pro tenant...\n');

  await integrationManager.shopify.setupIntegration(
    proTenant.id,
    'promerch.myshopify.com',
    'shpat_test_token'
  );

  await integrationManager.gumroad.setupIntegration(
    proTenant.id,
    'gum_test_api_key'
  );

  console.log('Integrations configured:');
  const status = integrationManager.getStatus(proTenant.id);
  console.log(`  Shopify: ${status.shopify ? 'Connected' : 'Not connected'}`);
  console.log(`  Gumroad: ${status.gumroad ? 'Connected' : 'Not connected'}\n`);

  // Sync product to all platforms
  console.log('Syncing product to all platforms...\n');

  const syncResults = await integrationManager.syncToAllPlatforms(
    mockProducts[0],
    proTenant.id
  );

  console.log('Sync results:');
  if (syncResults.shopify) {
    console.log(`  Shopify: ${syncResults.shopify.success ? 'Success' : 'Failed'}`);
    if (syncResults.shopify.id) console.log(`    Product ID: ${syncResults.shopify.id}`);
  }
  if (syncResults.gumroad) {
    console.log(`  Gumroad: ${syncResults.gumroad.success ? 'Success' : 'Failed'}`);
    if (syncResults.gumroad.id) console.log(`    Product ID: ${syncResults.gumroad.id}`);
  }

  // Upgrade tenant
  console.log('\nUpgrading free tenant to starter plan...\n');

  tenantManager.upgradePlan(freeTenant.id, 'starter');
  const upgradedTenant = tenantManager.getTenant(freeTenant.id);

  console.log(`${upgradedTenant?.name} upgraded to ${upgradedTenant?.plan}:`);
  console.log(`  New features:`);
  console.log(`    Auto-Linking: ${upgradedTenant?.settings.features.autoLinking ? 'Yes' : 'No'}`);
  console.log(`    Max Products: ${upgradedTenant?.settings.features.maxProducts}`);
}

// === RUN ALL DEMOS ===

async function runAllDemos() {
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║   StaticWaves POD Studio - Feature Demo                 ║');
  console.log('║   Product Linking | Price Lock-In | Multi-Region | SaaS ║');
  console.log('╚══════════════════════════════════════════════════════════╝');

  try {
    await demoProductLinking();
    await demoPriceLockIn();
    await demoMultiRegionFeeds();
    await demoWhiteLabelSaaS();

    console.log('\n✅ All demos completed successfully!\n');
  } catch (error) {
    console.error('\n❌ Demo error:', error);
  }
}

// Export for use in other files
export {
  runAllDemos,
  demoProductLinking,
  demoPriceLockIn,
  demoMultiRegionFeeds,
  demoWhiteLabelSaaS,
  mockVideos,
  mockProducts
};

// Run if executed directly
if (require.main === module) {
  runAllDemos();
}
