export enum LogType {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR'
}

export interface LogEntry {
  id: string;
  timestamp: string;
  message: string;
  type: LogType;
}

export interface QueueItem {
  id: string;
  name: string;
  status: 'pending' | 'uploading' | 'completed' | 'failed';
}

export interface EngineConfig {
  dropName: string;
  designCount: number;
  blueprintId: number;
  providerId: number;
  batchList: string;
}

export interface EditorState {
  scale: number;
  translateX: number;
  translateY: number;
}

// === Product Linking ===
export interface TikTokVideo {
  id: string;
  url: string;
  caption: string;
  hashtags: string[];
  views: number;
  likes: number;
  createdAt: string;
  metadata: VideoMetadata;
}

export interface VideoMetadata {
  duration: number;
  thumbnail: string;
  audioName?: string;
  mentions: string[];
  location?: string;
}

export interface ProductLink {
  id: string;
  videoId: string;
  productId: string;
  autoGenerated: boolean;
  confidence: number; // 0-1 confidence score
  tags: string[];
  createdAt: string;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  tags: string[];
  basePrice: number;
  regionalPricing: RegionalPricing;
  images: string[];
  blueprintId: number;
}

// === Price Lock-In ===
export interface PriceBucket {
  id: string;
  productId: string;
  price: number;
  region: Region;
  conversions: number;
  impressions: number;
  revenue: number;
  conversionRate: number;
  isActive: boolean;
  createdAt: string;
  lastUpdated: string;
}

export interface ConversionEvent {
  id: string;
  productId: string;
  priceBucketId: string;
  price: number;
  region: Region;
  source: string; // 'tiktok', 'organic', 'ad'
  timestamp: string;
}

// === Multi-Region ===
export enum Region {
  US = 'US',
  EU = 'EU',
  UK = 'UK'
}

export interface RegionalPricing {
  US: number;
  EU: number;
  UK: number;
}

export interface RegionalFeed {
  region: Region;
  products: Product[];
  currency: string;
  generatedAt: string;
  format: 'xml' | 'json' | 'csv';
}

// === Multi-Tenant SaaS ===
export interface Tenant {
  id: string;
  name: string;
  slug: string;
  plan: 'free' | 'starter' | 'pro' | 'enterprise';
  apiKey: string;
  settings: TenantSettings;
  createdAt: string;
  owner: string;
}

export interface TenantSettings {
  branding: {
    logo?: string;
    primaryColor: string;
    companyName: string;
  };
  integrations: {
    printifyApiKey?: string;
    tiktokAccessToken?: string;
    gumroadApiKey?: string;
    shopifyDomain?: string;
    shopifyAccessToken?: string;
  };
  features: {
    autoLinking: boolean;
    priceLockIn: boolean;
    multiRegion: boolean;
    maxProducts: number;
  };
}

export interface ShopifyIntegration {
  tenantId: string;
  shopDomain: string;
  accessToken: string;
  webhooks: string[];
  syncEnabled: boolean;
}

export interface GumroadIntegration {
  tenantId: string;
  apiKey: string;
  products: string[];
  autoSync: boolean;
}