import { TikTokVideo, Product, ProductLink } from '../types';

/**
 * Auto-links TikTok videos to products based on video metadata
 */
export class ProductLinker {
  private products: Product[];

  constructor(products: Product[]) {
    this.products = products;
  }

  /**
   * Generate product links from video metadata
   * Uses hashtags, caption keywords, and mentions to match products
   */
  async linkVideoToProducts(video: TikTokVideo): Promise<ProductLink[]> {
    const links: ProductLink[] = [];
    const videoKeywords = this.extractKeywords(video);

    for (const product of this.products) {
      const confidence = this.calculateMatchConfidence(videoKeywords, product);

      if (confidence > 0.3) { // Threshold for auto-linking
        links.push({
          id: this.generateId(),
          videoId: video.id,
          productId: product.id,
          autoGenerated: true,
          confidence,
          tags: this.generateTags(video, product),
          createdAt: new Date().toISOString()
        });
      }
    }

    // Sort by confidence, highest first
    return links.sort((a, b) => b.confidence - a.confidence);
  }

  /**
   * Extract keywords from video caption, hashtags, and audio
   */
  private extractKeywords(video: TikTokVideo): Set<string> {
    const keywords = new Set<string>();

    // Add hashtags (already cleaned)
    video.hashtags.forEach(tag => keywords.add(tag.toLowerCase()));

    // Extract words from caption
    const captionWords = video.caption
      .toLowerCase()
      .split(/\s+/)
      .filter(word => word.length > 3); // Filter out short words

    captionWords.forEach(word => keywords.add(word));

    // Add audio name keywords if available
    if (video.metadata.audioName) {
      const audioWords = video.metadata.audioName
        .toLowerCase()
        .split(/\s+/)
        .filter(word => word.length > 3);
      audioWords.forEach(word => keywords.add(word));
    }

    return keywords;
  }

  /**
   * Calculate confidence score (0-1) for video-product match
   */
  private calculateMatchConfidence(videoKeywords: Set<string>, product: Product): number {
    let score = 0;
    let matches = 0;

    // Check product tags
    for (const tag of product.tags) {
      if (videoKeywords.has(tag.toLowerCase())) {
        matches++;
        score += 0.2; // Strong match
      }
    }

    // Check product name
    const nameWords = product.name.toLowerCase().split(/\s+/);
    for (const word of nameWords) {
      if (videoKeywords.has(word)) {
        matches++;
        score += 0.15;
      }
    }

    // Check product description
    const descWords = product.description.toLowerCase().split(/\s+/);
    for (const word of descWords) {
      if (videoKeywords.has(word) && word.length > 4) {
        matches++;
        score += 0.05; // Weaker match
      }
    }

    // Normalize score to 0-1 range
    return Math.min(score, 1);
  }

  /**
   * Generate relevant tags for the product-video link
   */
  private generateTags(video: TikTokVideo, product: Product): string[] {
    const tags = new Set<string>();

    // Add relevant hashtags
    const relevantHashtags = video.hashtags.filter(tag =>
      product.tags.some(pTag => pTag.toLowerCase().includes(tag.toLowerCase()))
    );
    relevantHashtags.forEach(tag => tags.add(tag));

    // Add product tags
    product.tags.forEach(tag => tags.add(tag));

    // Add engagement level tag
    if (video.views > 100000) tags.add('viral');
    else if (video.views > 10000) tags.add('trending');

    // Add location tag if available
    if (video.metadata.location) {
      tags.add(`location:${video.metadata.location}`);
    }

    return Array.from(tags);
  }

  /**
   * Auto-generate product tags from video metadata
   */
  static autoGenerateTags(video: TikTokVideo): string[] {
    const tags = new Set<string>();

    // Add hashtags
    video.hashtags.forEach(tag => tags.add(tag));

    // Extract category keywords from caption
    const categoryKeywords = [
      'fashion', 'tech', 'beauty', 'fitness', 'home', 'art',
      'gaming', 'music', 'food', 'travel', 'lifestyle'
    ];

    const caption = video.caption.toLowerCase();
    categoryKeywords.forEach(keyword => {
      if (caption.includes(keyword)) {
        tags.add(keyword);
      }
    });

    // Add engagement-based tags
    if (video.views > 1000000) tags.add('viral');
    else if (video.views > 100000) tags.add('trending');
    else if (video.views > 10000) tags.add('popular');

    if (video.likes / video.views > 0.1) tags.add('high-engagement');

    // Add duration-based tags
    if (video.metadata.duration < 15) tags.add('short-form');
    else if (video.metadata.duration > 60) tags.add('long-form');

    return Array.from(tags);
  }

  private generateId(): string {
    return Math.random().toString(36).substr(2, 9);
  }
}
