import React, { useState } from 'react';
import { Link, TrendingUp, Tag, Zap } from 'lucide-react';
import { TikTokVideo, Product, ProductLink } from '../types';

interface ProductLinkerProps {
  videos: TikTokVideo[];
  products: Product[];
  onLinkCreated?: (link: ProductLink) => void;
}

export const ProductLinkerPanel: React.FC<ProductLinkerProps> = ({
  videos,
  products,
  onLinkCreated
}) => {
  const [selectedVideo, setSelectedVideo] = useState<TikTokVideo | null>(null);
  const [suggestedLinks, setSuggestedLinks] = useState<ProductLink[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);

  const handleAutoLink = async () => {
    if (!selectedVideo) return;

    setIsProcessing(true);

    // Simulate auto-linking process
    setTimeout(() => {
      const mockLinks: ProductLink[] = products.slice(0, 3).map((product, idx) => ({
        id: Math.random().toString(36).substr(2, 9),
        videoId: selectedVideo.id,
        productId: product.id,
        autoGenerated: true,
        confidence: 0.85 - (idx * 0.15),
        tags: ['auto-linked', ...product.tags.slice(0, 2)],
        createdAt: new Date().toISOString()
      }));

      setSuggestedLinks(mockLinks);
      setIsProcessing(false);
    }, 1500);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
      <div className="flex items-center gap-2 mb-4">
        <Link className="text-indigo-400" size={20} />
        <h3 className="text-lg font-bold text-slate-100">Content → Product Auto-Linker</h3>
      </div>

      <div className="space-y-4">
        {/* Video Selection */}
        <div>
          <label className="text-xs text-slate-400 mb-2 block">Select TikTok Video</label>
          <select
            className="w-full bg-slate-800 border border-slate-700 rounded px-3 py-2 text-sm"
            onChange={(e) => {
              const video = videos.find(v => v.id === e.target.value);
              setSelectedVideo(video || null);
              setSuggestedLinks([]);
            }}
          >
            <option value="">Choose a video...</option>
            {videos.map(video => (
              <option key={video.id} value={video.id}>
                {video.caption.slice(0, 50)}... ({video.views.toLocaleString()} views)
              </option>
            ))}
          </select>
        </div>

        {selectedVideo && (
          <>
            {/* Video Info */}
            <div className="bg-slate-800 rounded p-3 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-400">Hashtags:</span>
                <div className="flex gap-1 flex-wrap">
                  {selectedVideo.hashtags.map(tag => (
                    <span key={tag} className="text-xs bg-indigo-600/20 text-indigo-300 px-2 py-0.5 rounded">
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-400">Engagement:</span>
                <span className="text-xs text-slate-200">
                  {((selectedVideo.likes / selectedVideo.views) * 100).toFixed(1)}% Like Rate
                </span>
              </div>
            </div>

            {/* Auto-Link Button */}
            <button
              onClick={handleAutoLink}
              disabled={isProcessing}
              className="w-full flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white py-2 rounded font-semibold transition-colors disabled:opacity-50"
            >
              <Zap size={16} />
              {isProcessing ? 'Analyzing...' : 'Auto-Generate Product Links'}
            </button>

            {/* Suggested Links */}
            {suggestedLinks.length > 0 && (
              <div className="space-y-2">
                <label className="text-xs text-slate-400">Suggested Product Links</label>
                {suggestedLinks.map(link => {
                  const product = products.find(p => p.id === link.productId);
                  if (!product) return null;

                  return (
                    <div
                      key={link.id}
                      className="bg-slate-800 rounded p-3 flex items-center justify-between"
                    >
                      <div className="flex-1">
                        <div className="font-semibold text-sm text-slate-100">{product.name}</div>
                        <div className="flex items-center gap-2 mt-1">
                          <div className="flex items-center gap-1">
                            <TrendingUp size={12} className="text-emerald-400" />
                            <span className="text-xs text-emerald-400">
                              {(link.confidence * 100).toFixed(0)}% match
                            </span>
                          </div>
                          <div className="flex gap-1">
                            {link.tags.slice(0, 2).map(tag => (
                              <span key={tag} className="text-xs bg-slate-700 px-1.5 py-0.5 rounded">
                                {tag}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                      <button
                        onClick={() => onLinkCreated?.(link)}
                        className="bg-emerald-600 hover:bg-emerald-500 text-white px-3 py-1 rounded text-xs"
                      >
                        Link
                      </button>
                    </div>
                  );
                })}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
};
