#!/usr/bin/env python3
"""
StaticWaves Forge - Asset Pack Builder
Packages multiple assets into sellable marketplace bundles
"""

import os
import sys
import json
import zipfile
import shutil
from pathlib import Path
from datetime import datetime

class AssetPack:
    """Represents a complete asset pack"""

    def __init__(self, name, description="", price=0, tags=None):
        self.name = name
        self.description = description
        self.price = price
        self.tags = tags or []
        self.assets = []
        self.created_at = datetime.now().isoformat()
        self.version = "1.0.0"

    def add_asset(self, asset_path, asset_type="mesh"):
        """Add an asset to the pack"""
        self.assets.append({
            "path": str(asset_path),
            "type": asset_type,
            "name": Path(asset_path).stem
        })

    def to_dict(self):
        """Convert pack to dictionary"""
        return {
            "name": self.name,
            "description": self.description,
            "price": self.price,
            "tags": self.tags,
            "version": self.version,
            "created_at": self.created_at,
            "asset_count": len(self.assets),
            "assets": self.assets
        }

def generate_pack_metadata(pack):
    """Generate metadata JSON for the pack"""
    return json.dumps(pack.to_dict(), indent=2)

def generate_unity_package(pack, output_dir):
    """
    Generate Unity Asset Store compatible package
    Structure:
      - Assets/
      - Documentation/
      - package.json
    """
    pack_dir = Path(output_dir) / pack.name
    pack_dir.mkdir(parents=True, exist_ok=True)

    # Create directories
    assets_dir = pack_dir / "Assets" / pack.name
    docs_dir = pack_dir / "Documentation"
    assets_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)

    # Copy assets
    for asset in pack.assets:
        src = Path(asset["path"])
        if src.exists():
            dst = assets_dir / src.name
            shutil.copy2(src, dst)

    # Generate package.json
    package_json = {
        "name": f"com.staticwaves.{pack.name.lower().replace(' ', '_')}",
        "displayName": pack.name,
        "version": pack.version,
        "description": pack.description,
        "unity": "2020.3",
        "keywords": pack.tags
    }

    with open(pack_dir / "package.json", "w") as f:
        json.dump(package_json, f, indent=2)

    # Generate README
    readme = f"""# {pack.name}

{pack.description}

## Contents
- {len(pack.assets)} game-ready assets
- Optimized for Unity 2020.3+
- Includes LOD levels
- PBR materials

## Installation
1. Import package into Unity
2. Assets will appear in Assets/{pack.name}

## Tags
{', '.join(pack.tags)}

---
Generated by StaticWaves Forge
"""

    with open(docs_dir / "README.md", "w") as f:
        f.write(readme)

    # Create ZIP
    zip_path = Path(output_dir) / f"{pack.name}_Unity.zip"
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(pack_dir)
                zipf.write(file_path, arcname)

    # Clean up temp directory
    shutil.rmtree(pack_dir)

    print(f"✅ Unity package created: {zip_path}")
    return zip_path

def generate_unreal_package(pack, output_dir):
    """
    Generate Unreal Marketplace compatible package
    """
    pack_dir = Path(output_dir) / pack.name
    pack_dir.mkdir(parents=True, exist_ok=True)

    # Create Content directory
    content_dir = pack_dir / "Content" / pack.name
    content_dir.mkdir(parents=True, exist_ok=True)

    # Copy assets
    for asset in pack.assets:
        src = Path(asset["path"])
        if src.exists():
            dst = content_dir / src.name
            shutil.copy2(src, dst)

    # Generate .uplugin file
    uplugin = {
        "FileVersion": 3,
        "Version": 1,
        "VersionName": pack.version,
        "FriendlyName": pack.name,
        "Description": pack.description,
        "Category": "Content",
        "CreatedBy": "StaticWaves Forge",
        "CreatedByURL": "",
        "EngineVersion": "5.0.0",
        "CanContainContent": True
    }

    with open(pack_dir / f"{pack.name}.uplugin", "w") as f:
        json.dump(uplugin, f, indent=2)

    # Create ZIP
    zip_path = Path(output_dir) / f"{pack.name}_Unreal.zip"
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(pack_dir)
                zipf.write(file_path, arcname)

    shutil.rmtree(pack_dir)

    print(f"✅ Unreal package created: {zip_path}")
    return zip_path

def generate_roblox_package(pack, output_dir):
    """
    Generate Roblox Creator Store compatible package
    """
    pack_dir = Path(output_dir) / pack.name
    pack_dir.mkdir(parents=True, exist_ok=True)

    # Copy FBX files (Roblox uses FBX)
    for asset in pack.assets:
        src = Path(asset["path"])
        if src.exists():
            dst = pack_dir / src.name
            shutil.copy2(src, dst)

    # Generate metadata
    metadata = {
        "name": pack.name,
        "description": pack.description,
        "type": "Model",
        "tags": pack.tags
    }

    with open(pack_dir / "metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    # Create ZIP
    zip_path = Path(output_dir) / f"{pack.name}_Roblox.zip"
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(pack_dir)
                zipf.write(file_path, arcname)

    shutil.rmtree(pack_dir)

    print(f"✅ Roblox package created: {zip_path}")
    return zip_path

def generate_gumroad_package(pack, output_dir):
    """
    Generate Gumroad-ready package with all formats
    """
    pack_dir = Path(output_dir) / pack.name
    pack_dir.mkdir(parents=True, exist_ok=True)

    # Create subdirectories for each format
    unity_dir = pack_dir / "Unity"
    unreal_dir = pack_dir / "Unreal"
    roblox_dir = pack_dir / "Roblox"
    raw_dir = pack_dir / "Raw_Files"

    for d in [unity_dir, unreal_dir, roblox_dir, raw_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # Copy assets to all directories
    for asset in pack.assets:
        src = Path(asset["path"])
        if src.exists():
            # Copy to each format directory
            for dest_dir in [unity_dir, unreal_dir, roblox_dir, raw_dir]:
                shutil.copy2(src, dest_dir / src.name)

    # Generate comprehensive README
    readme = f"""# {pack.name}

{pack.description}

## Package Contents

This package includes {len(pack.assets)} professional 3D assets ready for immediate use.

### Included Formats
- **Unity/** - Unity-ready FBX files
- **Unreal/** - Unreal Engine-ready FBX files
- **Roblox/** - Roblox Studio-ready FBX files
- **Raw_Files/** - Original files (GLB, OBJ, FBX)

### Features
- Game-ready topology
- Optimized LOD levels
- PBR materials
- Clean UVs
- Professional quality

### Tags
{', '.join(pack.tags)}

### Version
{pack.version}

### License
Standard Royalty-Free License
- ✅ Use in commercial projects
- ✅ Modify and adapt
- ✅ No attribution required
- ❌ Cannot resell as-is

---

**Created with StaticWaves Forge**
AI-powered 3D asset generation platform

Questions? Support: support@staticwaves.io
"""

    with open(pack_dir / "README.txt", "w") as f:
        f.write(readme)

    # Generate metadata
    with open(pack_dir / "metadata.json", "w") as f:
        f.write(generate_pack_metadata(pack))

    # Create final ZIP
    zip_path = Path(output_dir) / f"{pack.name}.zip"
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                file_path = Path(root) / file
                arcname = file_path.relative_to(pack_dir.parent)
                zipf.write(file_path, arcname)

    shutil.rmtree(pack_dir)

    print(f"✅ Gumroad package created: {zip_path}")
    print(f"   Size: {zip_path.stat().st_size / 1024 / 1024:.2f} MB")
    return zip_path

def create_sample_pack():
    """Create a sample pack for testing"""
    pack = AssetPack(
        name="Fantasy_Creatures_Starter",
        description="25 stylized fantasy creatures with animations. Perfect for indie RPG games.",
        price=39,
        tags=["fantasy", "creatures", "lowpoly", "animated", "rpg", "indie"]
    )

    # In production, these would be actual generated assets
    # For now, we'll document the structure
    print("Sample pack structure:")
    print(json.dumps(pack.to_dict(), indent=2))

    return pack

def main():
    """Main entry point"""
    argv = sys.argv[1:]

    if len(argv) < 1:
        print("Usage: python build_pack.py <pack_name> [format] [output_dir]")
        print("Formats: unity, unreal, roblox, gumroad, all")
        print("\nExample: python build_pack.py Fantasy_Creatures gumroad ./output")
        sys.exit(1)

    pack_name = argv[0]
    format_type = argv[1].lower() if len(argv) > 1 else "gumroad"
    output_dir = argv[2] if len(argv) > 2 else "./packs"

    # Create sample pack
    pack = AssetPack(
        name=pack_name,
        description=f"Professional {pack_name} asset pack",
        price=39,
        tags=["game-ready", "3d", "assets"]
    )

    # In production, scan for generated assets
    # For now, create the package structure

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    if format_type == "unity":
        generate_unity_package(pack, output_dir)
    elif format_type == "unreal":
        generate_unreal_package(pack, output_dir)
    elif format_type == "roblox":
        generate_roblox_package(pack, output_dir)
    elif format_type == "gumroad":
        generate_gumroad_package(pack, output_dir)
    elif format_type == "all":
        generate_unity_package(pack, output_dir)
        generate_unreal_package(pack, output_dir)
        generate_roblox_package(pack, output_dir)
        generate_gumroad_package(pack, output_dir)
    else:
        print(f"❌ Unknown format: {format_type}")
        sys.exit(1)

    print(f"\n✅ Pack generation complete!")
    print(f"   Output directory: {output_dir}")

if __name__ == "__main__":
    main()
